sip:
  enable-log: ${local.sip.enable-log}
  port: ${local.sip.port}
  ip: ${local.sip.host}
  enable: ${local.sip.enable}

# ZLM配置
zlm:
  enable: ${local.zlm.enable:true}
  hook-enable: ${local.zlm.hook-enable:true}
  servers:
    - server-id: ${local.zlm.server-id:zlm-default}
      host: ${local.zlm.host:localhost}
      port: ${local.zlm.port:80}
      secret: ${local.zlm.secret:zlm}