spring:
  application:
    name: voglander
  profiles:
    active: dev,repo,inte

logging:
  config: classpath:log/logback-spring.xml
  level:
    root: INFO

server:
  port: 8081

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: default
    # 启用深度链接
    deep-linking: true
    # 显示扩展
    display-extensions: true
    # 显示操作ID
    display-operation-id: true
    # 排序
    operations-sorter: alpha
    tags-sorter: alpha
    # 尝试功能
    try-it-out-enabled: true
  # 分组配置
  group-configs:
    - group: 'default'
      display-name: '默认'
      paths-to-match: '/**'

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice,/zlm/**,/swagger-ui/**,/v3/api-docs/**
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
